# Generated by Django 5.0 on 2024-02-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_category_listing_comments_bid_watchlist_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Books", "Books"),
                    ("Home and Garden", "Home and Garden"),
                ],
                max_length=255,
            ),
        ),
    ]
