# Generated by Django 5.0 on 2024-02-14 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_category_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_name",
            new_name="category",
        ),
    ]
