# Generated by Django 5.0 on 2024-02-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_alter_listing_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.CharField(max_length=100),
        ),
    ]
